"""CLI: apply a recipe to a base config, writing a merged config (no training).

    python -m edge_ai_compression.recipes.apply \
        --recipe raspberry_pi_fast \
        --base-config edge_ai_compression/configs/experiments/smoke_cpu.yml \
        --out configs/generated/raspberry_pi_fast.yml

This ONLY generates configuration by deep-merging the recipe's compression /
hardware settings into the base config. It does not run any experiment.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

from edge_ai_compression.recipes.catalog import available_recipes, get_recipe


def deep_merge(base: dict[str, Any], overlay: dict[str, Any]) -> dict[str, Any]:
    """Recursively merge ``overlay`` into a copy of ``base`` (overlay wins)."""
    merged = dict(base)
    for key, value in overlay.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def apply_recipe(base_config: dict[str, Any], recipe_name: str) -> dict[str, Any]:
    """Return ``base_config`` deep-merged with the named recipe's overlay."""
    recipe = get_recipe(recipe_name)
    return deep_merge(base_config, recipe.to_config_overlay())


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="python -m edge_ai_compression.recipes.apply",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--recipe", required=True, help=f"One of: {', '.join(available_recipes())}.")
    p.add_argument("--base-config", type=Path, required=True, help="Base experiment YAML.")
    p.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output path (default: configs/generated/<recipe>.yml, git-ignored).",
    )
    args = p.parse_args(argv)

    if not args.base_config.is_file():
        print(f"Base config not found: {args.base_config}")
        return 2
    try:
        recipe = get_recipe(args.recipe)
    except KeyError as exc:
        print(str(exc))
        return 1

    base = yaml.safe_load(args.base_config.read_text(encoding="utf-8")) or {}
    merged = apply_recipe(base, args.recipe)

    out = args.out or Path("configs/generated") / f"{args.recipe}.yml"
    out.parent.mkdir(parents=True, exist_ok=True)
    header = (
        f"# Generated by recipe '{recipe.name}' applied to {args.base_config}.\n"
        f"# {recipe.description}\n"
        f"# Recommended export format: {recipe.export_format}\n"
    )
    out.write_text(header + yaml.safe_dump(merged, sort_keys=False), encoding="utf-8")
    print(f"Applied recipe '{recipe.name}' -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
